MvcNetCoreLinqToSql/Models/Empleado.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcNetCoreLinqToSql/Models/Enfermo.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class Enfermo
    {
        public string Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime? Fecha_Nac { get; set; }
        public string S { get; set; }
        public string NSS { get; set; }
    }
}

MvcNetCoreLinqToSql/Models/ErrorViewModel.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreLinqToSql/Models/ResumenEmpleados.cs
namespace MvcNetCoreLinqToSql.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaxSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }

    }
}

MvcNetCoreLinqToSql/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using MvcNetCoreLinqToSql.Repositories;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repoEmp;

        public EmpleadosController()
        {
            this.repoEmp = new RepositoryEmpleados();
        }

        public IActionResult DatosEmpleados()
        {
            ViewData["OFICIOS"] = this.repoEmp.GetOficios();
            ViewData["DEPARTAMENTOS"] = this.repoEmp.GetDepartamentos();
            return View();
        }

        [HttpPost]
        public IActionResult DatosEmpleados(string? oficio, int departamento)
        {
            ViewData["OFICIOS"] = this.repoEmp.GetOficios();
            ViewData["DEPARTAMENTOS"] = this.repoEmp.GetDepartamentos();
            ResumenEmpleados model = null;

            if (oficio != null)
            {
                model = this.repoEmp.GetEmpleadosOficio(oficio);
            }
            if (departamento != 0)
            {
                model = this.repoEmp.GetEmpleadosDepartamento(departamento);
            }

            return View(model);
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repoEmp.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Detalles(int id)
        {
            Empleado empleado = this.repoEmp.FindEmpleado(id);
            return View(empleado);
        }

        public IActionResult BuscarEmpleados()
        {
            List<Empleado> empleados = this.repoEmp.GetEmpleados();
            return View(empleados);
        }

        [HttpPost]
        public IActionResult BuscarEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repoEmp.GetEmpleadosOficioSalario(oficio, salario);
            if (empleados == null)
            {
                ViewData["MENSAJE"] = "No existen registros con oficio " + oficio + " ni salario mayor a " + salario;
                return View();
            }
            else
            {
                return View(empleados);
            }
        }
    }
}

MvcNetCoreLinqToSql/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using MvcNetCoreLinqToSql.Repositories;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class EnfermosController : Controller
    {
        private RepositoryEnfermos repoEnf;

        public EnfermosController()
        {
            this.repoEnf = new RepositoryEnfermos();
        }
        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repoEnf.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(string inscripcion)
        {
            Enfermo enfermo = this.repoEnf.FindEnfermo(inscripcion);
            return View(enfermo);
        }

        public async Task<IActionResult> Delete(string inscripcion)
        {
            await this.repoEnf.DeleteAsync(inscripcion);
            return RedirectToAction("Index");
        }
    }
}

MvcNetCoreLinqToSql/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreLinqToSql.Models;
using System.Diagnostics;

namespace MvcNetCoreLinqToSql.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreLinqToSql/Views/Empleados/BuscarEmpleados.cshtml
@model List<Empleado>

<div class="container mt-5">
    <h1>Buscador Empleados</h1>

    <form method="post">
        <label>Oficio: </label>
        <input class="form-control" type="text" name="oficio" required />
        <label>Salario: </label>
        <input class="form-control" type="number" name="salario" required />
        <br/>
        <button class="btn btn-success">
            Buscar Empleados
        </button>
    </form>
    <hr/>
    <h2 style="color: blue">
        @ViewData["MENSAJE"]
    </h2>
    <hr/>
    @if (Model != null)
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Apellido</th>
                    <th>Oficio</th>
                    <th>Salario</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Empleado emp in Model)
                {
                    <tr>
                        <td>@emp.Apellido</td>
                        <td>@emp.Oficio</td>
                        <td>@emp.Salario</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

MvcNetCoreLinqToSql/Views/Empleados/DatosEmpleados.cshtml
@model ResumenEmpleados?

@{
    List<string> oficios = ViewData["OFICIOS"] as List<string>;
    List<int> departamentos = ViewData["DEPARTAMENTOS"] as List<int>;
}

<div class="container mt-5">
    <h1>Lambda Empleados Oficio</h1>

    @* <form method="post">
        <label>Introduzca oficio: </label>
        <input type="text" class="form-control" name="oficio" />
        <br/>
        <button class="btn btn-success">
            Mostrar Resumen
        </button>
    </form> *@

    <form method="post">
        <label>Introduzca oficio: </label>
        <select name="oficio">
            @foreach(string oficio in oficios)
            {
                <option value="@oficio">@oficio</option>
            }
        </select>
        <br />
        <button class="btn btn-success">
            Mostrar Resumen
        </button>
    </form>


    <form method="post">
        <label>Introduzca departamento: </label>
        <select name="departamento">
            @foreach (int departamento in departamentos)
            {
                <option value="@departamento">@departamento</option>
            }
        </select>
        <br />
        <button class="btn btn-success">
            Mostrar Resumen
        </button>
    </form>
    <hr/>
    @if (Model != null)
    {
        <ul class="list-group">
            <li class="list-group-item">
                Personas: @Model.Personas
            </li>
            <li class="list-group-item">
                Maximo Salario: @Model.MaxSalario
            </li>
            <li class="list-group-item">
                Media Salarial: @Model.MediaSalarial
            </li>
        </ul>
        <hr/>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Apellido</th>
                    <th>Oficio</th>
                    <th>Salario</th>
                </tr>
            </thead>
            <tbody>
                @foreach(Empleado emp in Model.Empleados)
                {
                    <tr>
                        <td>@emp.Apellido</td>
                        <td>@emp.Oficio</td>
                        <td>@emp.Salario</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

MvcNetCoreLinqToSql/Views/Empleados/Detalles.cshtml
@model Empleado

<div class="container mt-5">
    <h1>Detalles Empleado</h1>

    <p>
        <a asp-controller="Empleados" asp-action="Index" class="btn btn-info">
            Atras
        </a>
    </p>

    <ul class="list-group">
        <li class="list-group-item">
            Apellido: @Model.Apellido
        </li>
        <li class="list-group-item">
            Oficio: @Model.Oficio
        </li>
        <li class="list-group-item">
            Salario: @Model.Salario
        </li>
        <li class="list-group-item">
            Departamento: @Model.IdDepartamento
        </li>
    </ul>
</div>

MvcNetCoreLinqToSql/Views/Empleados/Index.cshtml
@model List<Empleado>

<div class="container mt-5">
    <h1>Empleados Linq To Sql</h1>
    <hr/>
    <ul class="list-group">
        @foreach (Empleado emp in Model)
        {
            <li class="list-group-item">
                @emp.Apellido - @emp.Oficio -
                <a asp-controller="Empleados" asp-action="Detalles" asp-route-id="@emp.IdEmpleado" class="btn btn-primary">
                    Detalles
                </a>
            </li>
        }
    </ul>
</div>

MvcNetCoreLinqToSql/Views/Enfermos/Details.cshtml
@model Enfermo

<div class="container mt-5">
    <h1>Enfermo Detalles</h1>
    <hr/>
    <p>
        <a asp-controller="Enfermos" asp-action="Index" class="btn btn-info">
            Atras
        </a>
    </p>
    <hr/>
    <ul class="list-group">
        <li class="list-group-item">
            Inscripcion: @Model.Inscripcion
        </li>
        <li class="list-group-item">
            Apellido: @Model.Apellido
        </li>
        <li class="list-group-item">
            Direccion: @Model.Direccion
        </li>
        <li class="list-group-item">
            Fecha Nacimiento: @Model.Fecha_Nac
        </li>
        <li class="list-group-item">
            Genero: @Model.S
        </li>
        <li class="list-group-item">
            NSS: @Model.NSS
        </li>
    </ul>
</div>

MvcNetCoreLinqToSql/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<div class="container mt-5">
    <h1>Enfermos Linq To Sql</h1>
    <hr/>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Inscripcion</th>
                <th>Apellido</th>
                <th>Direccion</th>
                <th>-</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Enfermo enf in Model)
            {
                <tr>
                    <td>@enf.Inscripcion</td>
                    <td>@enf.Apellido</td>
                    <td>@enf.Direccion</td>
                    <td>
                        <a asp-controller="Enfermos" asp-action="Details" class="btn btn-primary"
                            asp-route-inscripcion="@enf.Inscripcion">
                            Detalles
                        </a>
                        @Html.ActionLink("Delete", "Delete", "Enfermos", new {inscripcion = enf.Inscripcion}, new{@class = "btn btn-danger"})
                    </td>
                </tr>   
            }
        </tbody>
    </table>
</div>

MvcNetCoreLinqToSql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreLinqToSql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreLinqToSql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreLinqToSql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreLinqToSql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Empleados" asp-action="BuscarEmpleados" class="nav-link text-dark">Buscar Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Enfermos" asp-action="Index" class="nav-link text-dark">Enfermos</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Empleados" asp-action="DatosEmpleados" class="nav-link text-dark">Lambda Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcNetCoreLinqToSql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>